// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-d6-VVy5bn_7Y0WcJazwej0lh4PZfnc',
    appId: '1:120341177152:web:aaf63c2e651a6f89bf50a5',
    messagingSenderId: '120341177152',
    projectId: 'lockguardv2',
    authDomain: 'lockguardv2.firebaseapp.com',
    databaseURL: 'https://lockguardv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lockguardv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lbjO3zdKs3V86m3v62McqjXymdg1OlY',
    appId: '1:120341177152:android:91f7eca8cebadb67bf50a5',
    messagingSenderId: '120341177152',
    projectId: 'lockguardv2',
    databaseURL: 'https://lockguardv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lockguardv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUoG_X41rK3wbT-pW2ixKqh0BR7kBvjY',
    appId: '1:120341177152:ios:216eb86386014047bf50a5',
    messagingSenderId: '120341177152',
    projectId: 'lockguardv2',
    databaseURL: 'https://lockguardv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lockguardv2.firebasestorage.app',
    iosBundleId: 'com.example.lockguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUoG_X41rK3wbT-pW2ixKqh0BR7kBvjY',
    appId: '1:120341177152:ios:216eb86386014047bf50a5',
    messagingSenderId: '120341177152',
    projectId: 'lockguardv2',
    databaseURL: 'https://lockguardv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lockguardv2.firebasestorage.app',
    iosBundleId: 'com.example.lockguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-d6-VVy5bn_7Y0WcJazwej0lh4PZfnc',
    appId: '1:120341177152:web:8b139652bb9af9e9bf50a5',
    messagingSenderId: '120341177152',
    projectId: 'lockguardv2',
    authDomain: 'lockguardv2.firebaseapp.com',
    databaseURL: 'https://lockguardv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lockguardv2.firebasestorage.app',
  );
}
